[Node]
Testnet = true

[Opera]
AllowSnapsync = true

[Emitter.Validator]

# update with your validator ID
ID = 0

# update with your validator public key
PubKeyString = ""

# update with your validator password file path
PasswordFilePath = ""
