{
 "title": "X1 Nodes",
 "description": "Blockchain metrics overview dashboard.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(up,instance)" } }
  ]
 },
 "panels": [
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total RPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rpc_success{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(rpc_failure{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "RPC Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_requests{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(p2p_ingress{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "ingress"
    },
    {
     "expr": "sum(rate(p2p_egress{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "egress"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(p2p_peers{instance=~\"$instance\"})",
     "legendFormat": "peers"
    },
    {
     "expr": "max(rate(p2p_dials{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "dials"
    },
    {
     "expr": "max(rate(p2p_serves{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "serves"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_block{instance=~\"$instance\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_receipt{instance=~\"$instance\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_block{instance=~\"$instance\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(txpool_pending{instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(txpool_queued{instance=~\"$instance\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(txpool_local{instance=~\"$instance\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(chain_head_header{instance=~\"$instance\"})",
     "legendFormat": "header"
    },
    {
     "expr": "max(chain_head_receipt{instance=~\"$instance\"})",
     "legendFormat": "receipt"
    },
    {
     "expr": "max(chain_head_block{instance=~\"$instance\"})",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(txpool_pending{instance=~\"$instance\"})",
     "legendFormat": "executable"
    },
    {
     "expr": "max(txpool_queued{instance=~\"$instance\"})",
     "legendFormat": "gapped"
    },
    {
     "expr": "max(txpool_local{instance=~\"$instance\"})",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Block Age",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "expr": "avg(chain_block_age / 1000000)", "legendFormat": "age" }
   ]
  },
  {
   "title": "Pending Transactions Per Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Queued Transactions Per Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Local Transactions Per Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(chain_execution{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "avg(chain_validation{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "avg(chain_write{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "avg(chain_account_reads{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "avg(chain_account_updates{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "avg(chain_account_hashes{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "avg(chain_account_commits{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "avg(chain_storage_reads{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "avg(chain_storage_updates{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "avg(chain_storage_hashes{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "avg(chain_storage_commits{quantile=\"$quantile\", instance=~\"$instance\"})",
     "legendFormat": "storage commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation (Total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(txpool_valid{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "valid"
    },
    {
     "expr": "sum(rate(txpool_invalid{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "invalid"
    },
    {
     "expr": "sum(rate(txpool_underpriced{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "underpriced"
    },
    {
     "expr": "sum(rate(txpool_pending_discard{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "executable discard"
    },
    {
     "expr": "sum(rate(txpool_pending_replace{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "executable replace"
    },
    {
     "expr": "sum(rate(txpool_pending_ratelimit{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "sum(rate(txpool_pending_nofunds{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "sum(rate(txpool_queued_discard{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "sum(rate(txpool_queued_replace{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "sum(rate(txpool_queued_ratelimit{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "sum(rate(txpool_queued_nofunds{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Transaction Receipt Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(chain_txs[$interval]))\n",
     "legendFormat": "TXs"
    }
   ]
  },
  {
   "title": "Transaction Recipt Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(rate(chain_txs[$interval]))\n",
     "legendFormat": "TXs"
    }
   ]
  },
  {
   "title": "Events Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(opera_events[$interval]))\n",
     "legendFormat": "TXs"
    }
   ]
  },
  {
   "title": "Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(rate(opera_events[$interval]))",
     "legendFormat": "TXs"
    }
   ]
  },
  {
   "title": "Events Confirmed Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(opera_events_confirmed[$interval]))\n",
     "legendFormat": "TXs"
    }
   ]
  },
  {
   "title": "Events Confirmed Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(rate(opera_events_confirmed[$interval]))\n",
     "legendFormat": "TXs"
    }
   ]
  },
  {
   "title": "Events Connected Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(opera_events_connected[$interval]))\n",
     "legendFormat": "TXs"
    }
   ]
  },
  {
   "title": "Events Connected Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(rate(opera_events_connected[$interval]))\n",
     "legendFormat": "TXs"
    }
   ]
  },
  { "title": "Trie Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Clean cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(trie_memcache_clean_read{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(rate(trie_memcache_clean_write{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(trie_memcache_gc_size{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "gc"
    },
    {
     "expr": "sum(rate(trie_memcache_flush_size{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "overflow"
    },
    {
     "expr": "sum(rate(trie_memcache_commit_size{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "commit"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Avg Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(rate(system_disk_readbytes{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(irate(system_disk_writebytes{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Avg Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "avg(system_memory_used)", "legendFormat": "Memory Used" }
   ]
  }
 ]
}