name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update apt
        run: sudo apt update

      - name: Install argon2
        run: sudo apt install -y argon2

      - name: Golang dependency
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run unit tests
        run: go test -v ./...

      - name: Build
        run: make x1

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/x1"
          token: ${{ secrets.GITHUB_TOKEN }}
