name: Check build

on:
  push:
  pull_request:
    branches:
      - develop
      - master

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update apt
        run: sudo apt update

      - name: Install argon2
        run: sudo apt install -y libargon2-dev

      - name: Golang dependency
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run unit tests
        run: go test -v ./...

      - name: Build
        run: make x1

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: opera
          path: ./build/x1
